AWSTemplateFormatVersion: '2010-09-09'
Description: Demo Lambda function with cloudformation.
Resources:
  awslambdacloudformation:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Code:
        ZipFile: |
          def handler(event, context):
            return{
            'message':'hello'
            }
      Description: Invoke a function during stack creation.
  awslambdacloudformationPOST:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Code:
        ZipFile: |
          def handler(event, context):
            return{
            'message':'hello'
            }
      Description: Invoke a function during stack creation.
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Path: /
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt awslambdacloudformation.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'
  LambdaPermissionPost:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt awslambdacloudformationPOST.Arn
      Action: lambda:InvokeFunction
      Principal: 'apigateway.amazonaws.com'
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "department"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
        - 
          AttributeName: "department"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "employee"